import { cardType } from "./types";

export const cardData: cardType[] = [
    {
        image: "/images/ext_01.png",
        name: "",
        story: "",
        bedroom: 0,
        bathroom: "",
        price: 350,
    },
    {
        image: "/images/ext_02.jpeg",
        name: "",
        story: "",
        bedroom: 1,
        bathroom: "",
        price: 350,
    },
    {
        image: "/images/ext_03.jpeg",
        name: "",
        story: "",
        bedroom: 2,
        bathroom: "",
        price: 375,
    },
    {
        image: "/images/ext_04.jpeg",
        name: "",
        story: "",
        bedroom: 3,
        bathroom: "",
        price: 375,
    },
    {
        image: "/images/ext_05.jpeg",
        name: "",
        story: "",
        bedroom: 3,
        bathroom: "",
        price: 400,
    },
    {
        image: "/images/ext_06.jpeg",
        name: "",
        story: "",
        bedroom: 0,
        bathroom: "",
        price: 400,
    },
    {
        image: "/images/ext_07.jpeg",
        name: "",
        story: "",
        bedroom: 0,
        bathroom: "",
        price: 425,
    },
    {
        image: "/images/ext_08.jpeg",
        name: "",
        story: "",
        bedroom: 0,
        bathroom: "",
        price: 450,
    },
    {
        image: "/images/ext_09.jpeg",
        name: "",
        story: "",
        bedroom: 0,
        bathroom: "",
        price: 470,
    },
    {
        image: "/images/ext_10.jpeg",
        name: "",
        story: "3",
        bedroom: 6,
        bathroom: "",
      price: 500,
        PBL: 1
    },
    {
        image: "/images/ext_11.jpeg",
        name: "",
        story: 2,
        bedroom: 4,
        bathroom: "",
        price: 500,
    },
    {
        image: "/images/ext_12.jpeg",
        name: "",
        story: 2,
        bedroom: 4,
        bathroom: "",
        price: 500,
    },
    {
        image: "/images/ext_13.jpeg",
        name: "",
        story: "3",
        bedroom: 6,
        bathroom: "",
        price: 500,
    },
    {
        image: "/images/ext_14.jpeg",
        name: "",
        story: "",
        bedroom: 5,
        bathroom: "",
        price: 1000,
    },
    {
        image: "/images/ext_15.jpeg",
        name: "",
        story: "",
        bedroom: 5,
        bathroom: "",
        price: 1000,
    },
]