import { cardType } from "./types";

export const cardData: cardType[] = [
    {
        key: 1,
        image: "/images/ext_01.png",
        name: "",
        story: 2,
        bedroom: 2,
        bathroom: "",
        price: 350,
    },
    {
        key: 2,
        image: "/images/ext_02.jpeg",
        name: "",
        story: 2,
        bedroom: 2,
        bathroom: "",
        price: 350,
    },
    {
        key: 3,
        image: "/images/ext_03.jpeg",
        name: "",
        story: 3,
        bedroom: 2,
        bathroom: "",
        price: 375,
    },
    {
        key: 4,
        image: "/images/ext_04.jpeg",
        name: "",
        story: "",
        bedroom: 3,
        bathroom: "",
        price: 375,
    },
    {
        key: 5,
        image: "/images/ext_05.jpeg",
        name: "",
        story: "",
        bedroom: 3,
        bathroom: "",
        price: 400,
    },
    {
        key: 6,
        image: "/images/ext_06.jpeg",
        name: "",
        story: "",
        bedroom: 0,
        bathroom: "",
        price: 400,
    },
    {
        key: 7,
        image: "/images/ext_07.jpeg",
        name: "",
        story: "",
        bedroom: 0,
        bathroom: "",
        price: 425,
    },
    {
        key: 8,
        image: "/images/ext_08.jpeg",
        name: "",
        story: "",
        bedroom: 0,
        bathroom: "",
        price: 450,
    },
    {
        key: 9,
        image: "/images/ext_09.jpeg",
        name: "",
        story: "",
        bedroom: 0,
        bathroom: "",
        price: 470,
    },
    {
        key: 10,
        image: "/images/ext_10.jpeg",
        name: "",
        story: "3",
        bedroom: 6,
        bathroom: "",
      price: 500,
        PBL: 1
    },
    {
        key: 11,
        image: "/images/ext_11.jpeg",
        name: "",
        story: 2,
        bedroom: 4,
        bathroom: "",
        price: 500,
    },
    {
        key: 12,
        image: "/images/ext_12.jpeg",
        name: "",
        story: 2,
        bedroom: 4,
        bathroom: "",
        price: 500,
    },
    {
        key: 13,
        image: "/images/ext_13.jpeg",
        name: "",
        story: "3",
        bedroom: 6,
        bathroom: "",
        price: 500,
    },
    {
        key: 14,
        image: "/images/ext_14.jpeg",
        name: "",
        story: "",
        bedroom: 5,
        bathroom: 2,
        price: 1000,
    },
    {
        key: 15,
        image: "/images/ext_15.jpeg",
        name: "",
        story: "",
        bedroom: 5,
        bathroom: 2,
        price: 1000,
    },
]

export const imageSlide = [
    {
        key: 1,
        heading: "Discover what to build",
        images: "/images/slideImage1.png",

    },
    {
        key: 2,
        heading: "Visualize your home in 3D/VR/4K Renders",
        video: "/images/slideVideo.mp4"
    },
    {
        key: 3,
        heading: "Track your home as it comes to life",
        images: "/images/slideImage2.png"
    },
    {
        key: 4,
        heading: "Smart home living",
        images: "/images/slideImage3.png"
    },
]

